{% if from_image is defined -%}
FROM {{ from_image }}

{% endif -%}
{% if image_preparation is defined -%}
# Preparing base image
{% for command_line in image_preparation -%}
RUN {{ command_line }}
{% endfor %}
{% endif -%}
#Building the environment
WORKDIR /root
RUN {{ python }} -m venv venv
RUN ./venv/bin/python -m pip install --upgrade pip
COPY dist/duoauthproxy_installer-0.1.0.dev0-py3-none-any.whl ./
RUN ./venv/bin/pip install --upgrade --extra-index-url https://test.pypi.org/simple/ duoauthproxy_installer-0.1.0.dev0-py3-none-any.whl "devautotools==0.1.2.dev4"
RUN ./venv/bin/pip install --upgrade rpmvenv virtualenv
ENV PATH=/root/venv/bin:$PATH

RUN mkdir /root/RPMS
VOLUME ["/root/RPMS"]

ENTRYPOINT ["python", "-m", "duoauthproxy_installer", "DuoAuthProxyInstaller", "{{ version_tag }}", "__call__", "--target_install_path", "{{ target_install_path }}", "--dist_dir", "{{ dist_dir }}", "{{ release_tag }}"]
