{% if from_image is defined -%}
FROM {{ from_image }}

{% endif -%}
{% if image_preparation is defined -%}
# Preparing base image
{% for command_line in image_preparation -%}
RUN {{ command_line }}
{% endfor %}
{% endif -%}
#Building the environment
WORKDIR /root
RUN python3 -m venv venv
RUN ./venv/bin/python -m pip install --upgrade pip
COPY dist/duoauthproxy_installer-0.1.0.dev0-py3-none-any.whl ./
RUN ./venv/bin/python -m pip install --upgrade duoauthproxy_installer-0.1.0.dev0-py3-none-any.whl
ENV PATH=/root/venv/bin:$PATH
RUN mkdir dist

VOLUME ["/root/dist"]

ENTRYPOINT ["python", "-m", "duoauthproxy_installer", "DuoAuthProxyInstaller", "{{ version_tag }}", "__call__", "--target_install_path", "{{ target_install_path }}", "{{ release_tag }}"]
