%{!?python_sitearch: %global python_sitearch %(%{__python} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(1))")}
%define debug_package %{nil}
%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%define _python_version 3.8.16

Name:           duoauthproxy-python
Version:        6.2.0
Release:        1%{?dist}
Summary:        Interpreter of the Python programming language (custom %{_python_version})

License:        Python
URL:            https://www.python.org/
Source0:        https://dl.duosecurity.com/duoauthproxy-%{version}-src.tgz
Patch0:			config.mk.patch

BuildRequires:  bzip2-devel
BuildRequires:  chkconfig
BuildRequires:  chrpath
BuildRequires:  diffutils
BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  gdbm-devel
BuildRequires:  libffi-devel
BuildRequires:  libuuid-devel
BuildRequires:  make
BuildRequires:  openssl-devel
BuildRequires:  perl
BuildRequires:  python3
BuildRequires:  readline-devel
BuildRequires:  selinux-policy-devel
BuildRequires:  sqlite-devel
BuildRequires:  tk-devel
BuildRequires:  uuid-devel
BuildRequires:  xz-devel
Conflicts:		python38-altinstall-duoauthproxy

%description
Python is an accessible, high-level, dynamically typed, interpreted programming
language, designed with an emphasis on code readability.
It includes an extensive standard library, and has a vast ecosystem of
third-party libraries.

This is an apparently customized python %{_python_version} version shipped with duoauthproxy-%{version}

%prep
%setup -q -n duoauthproxy-%{version}-src

%build
env CXX=/usr/bin/c++ make python

%install
rm -rf %{buildroot}
mkdir --parents %{buildroot}/opt/duoauthproxy/
mv duoauthproxy-build/* %{buildroot}/opt/duoauthproxy
for python_lib in %{buildroot}/opt/duoauthproxy/usr/local/lib/python3.8/lib-dynload/*.so; do
	if chrpath %{buildroot}/opt/duoauthproxy/usr/local/lib/python3.8/lib-dynload/$(basename $python_lib); then
		chrpath -r /opt/duoauthproxy/usr/local/lib %{buildroot}/opt/duoauthproxy/usr/local/lib/python3.8/lib-dynload/$(basename $python_lib)
	fi
done 
cp %{_builddir}/duoauthproxy-%{version}-src/*.py %{buildroot}/opt/duoauthproxy/usr/local/lib/python3.8/
# Compress man page
%{__gzip} --name --best %{buildroot}/opt/duoauthproxy/usr/local/share/man/man1/python3.8.1
rm %{buildroot}/opt/duoauthproxy/usr/local/share/man/man1/python3.1
# Remove the bytecode generated by the installer. The bytecode is unusable because of mtime not being set correctly.
find %{buildroot}/opt/duoauthproxy/ -type f -name '*.pyc' -delete
 
%files
/opt/duoauthproxy/usr/local/bin/2to3
/opt/duoauthproxy/usr/local/bin/2to3-3.8
/opt/duoauthproxy/usr/local/bin/idle3
/opt/duoauthproxy/usr/local/bin/idle3.8
/opt/duoauthproxy/usr/local/bin/pip
/opt/duoauthproxy/usr/local/bin/pip3
/opt/duoauthproxy/usr/local/bin/pip3.8
/opt/duoauthproxy/usr/local/bin/pydoc3
/opt/duoauthproxy/usr/local/bin/pydoc3.8
/opt/duoauthproxy/usr/local/bin/python3
/opt/duoauthproxy/usr/local/bin/python3-config
/opt/duoauthproxy/usr/local/bin/python3.8
/opt/duoauthproxy/usr/local/bin/python3.8-config
/opt/duoauthproxy/usr/local/bin/wheel
/opt/duoauthproxy/usr/local/include/python3.8
/opt/duoauthproxy/usr/local/lib/libpython3.8.a
/opt/duoauthproxy/usr/local/lib/pkgconfig/python-3.8-embed.pc
/opt/duoauthproxy/usr/local/lib/pkgconfig/python-3.8.pc
/opt/duoauthproxy/usr/local/lib/pkgconfig/python3-embed.pc
/opt/duoauthproxy/usr/local/lib/pkgconfig/python3.pc
/opt/duoauthproxy/usr/local/lib/python3.8
%doc /opt/duoauthproxy/usr/local/share/man/man1/python3.8.1.gz

%changelog
* Thu Nov 30 2024 Irving Leonard <mm-irvingleonard@github.com> 6.2.0-1
- Upgraded to duoauthproxy 6.2.0 and renamed the package from python38-altinstall-duoauthproxy
* Mon Dec 7 2020 Irving Leonard <mm-irvingleonard@github.com> 5.1.1-1
- Upgraded to duoauthproxy 5.1.1
* Tue Nov 10 2020 Irving Leonard <mm-irvingleonard@github.com> 5.1.0-1
- Upgraded to duoauthproxy 5.1.0
* Wed Sep 30 2020 Irving Leonard <mm-irvingleonard@github.com> 5.0.2-1
- Upgraded to duoauthproxy 5.0.2
* Wed Aug 19 2020 Irving Leonard <mm-irvingleonard@github.com> 5.0.0-2
- Upgraded to duoauthproxy 5.0.0
* Wed Jul 22 2020 Irving Leonard <mm-irvingleonard@github.com> 4.0.2-1
- Upgraded to duoauthproxy 4.0.2
* Fri Jul 17 2020 Irving Leonard <mm-irvingleonard@github.com> 4.0.1-1
- Initial RPM release
